import { BaseSeeder } from '@adonisjs/lucid/seeders'
import ConditionTemplate from '#models/condition_template'

/**
 * Condition Templates Seeder
 *
 * Seeds the 3 validated packs:
 * - Pack Rural NB v1.0 (D23)
 * - Pack Condo NB v1.0 (D2)
 * - Pack Financé NB v1.0 (D3)
 *
 * Plus universal conditions that apply to all transactions.
 */
export default class ConditionTemplatesSeeder extends BaseSeeder {
  async run() {
    // ============================================================
    // UNIVERSAL CONDITIONS (all transactions)
    // ============================================================

    await ConditionTemplate.createMany([
      // Step 2: En négociation
      {
        labelFr: 'Pré-qualification / pré-approbation vérifiée',
        labelEn: 'Pre-qualification / pre-approval verified',
        level: 'required',
        sourceType: 'industry',
        step: 2,
        appliesWhen: {},
        pack: 'universal',
        order: 1,
        isDefault: true,
        isActive: true,
        deadlineReference: null, // No deadline - pre-offer
        defaultDeadlineDays: null,
      },
      {
        labelFr: 'Motivation acheteur confirmée',
        labelEn: 'Buyer motivation confirmed',
        level: 'recommended',
        sourceType: 'best_practice',
        step: 2,
        appliesWhen: {},
        pack: 'universal',
        order: 2,
        isDefault: true,
        isActive: true,
        deadlineReference: null,
        defaultDeadlineDays: null,
      },

      // Step 3: Offre acceptée
      {
        labelFr: 'Inspection générale commandée',
        labelEn: 'General inspection ordered',
        level: 'required',
        sourceType: 'industry',
        step: 3,
        appliesWhen: {},
        pack: 'universal',
        order: 1,
        isDefault: true,
        isActive: true,
        deadlineReference: 'acceptance',
        defaultDeadlineDays: 3, // 3 days after acceptance to order
      },
      {
        labelFr: 'Résultats inspection — acceptables',
        labelEn: 'Inspection results — acceptable',
        level: 'required',
        sourceType: 'industry',
        step: 3,
        appliesWhen: {},
        pack: 'universal',
        order: 2,
        isDefault: true,
        isActive: true,
        deadlineReference: 'acceptance',
        defaultDeadlineDays: 7, // 7 days after acceptance
      },
      {
        labelFr: 'Dépôt initial reçu',
        labelEn: 'Initial deposit received',
        level: 'blocking',
        sourceType: 'legal',
        step: 3,
        appliesWhen: {},
        pack: 'universal',
        order: 3,
        isDefault: true,
        isActive: true,
        deadlineReference: 'acceptance',
        defaultDeadlineDays: 2, // 48h after acceptance
      },

      // Step 4: Période conditionnelle
      {
        labelFr: 'Toutes conditions contractuelles levées',
        labelEn: 'All contractual conditions waived',
        level: 'blocking',
        sourceType: 'legal',
        step: 4,
        appliesWhen: {},
        pack: 'universal',
        order: 1,
        isDefault: true,
        isActive: true,
        deadlineReference: 'acceptance',
        defaultDeadlineDays: 10, // 10 days conditional period
      },

      // Step 5: Ferme en attente
      {
        labelFr: 'Avocat confirmé + dossier ouvert',
        labelEn: 'Lawyer confirmed + file opened',
        level: 'blocking',
        sourceType: 'legal',
        step: 5,
        appliesWhen: {},
        pack: 'universal',
        order: 1,
        isDefault: true,
        isActive: true,
        deadlineReference: 'closing',
        defaultDeadlineDays: -14, // 14 days before closing
      },

      // Step 7: Jour de clôture
      {
        labelFr: 'Signatures complétées',
        labelEn: 'Signatures completed',
        level: 'blocking',
        sourceType: 'legal',
        step: 7,
        appliesWhen: {},
        pack: 'universal',
        order: 1,
        isDefault: true,
        isActive: true,
        deadlineReference: 'closing',
        defaultDeadlineDays: 0, // On closing day
      },
      {
        labelFr: 'Fonds transférés / déboursés',
        labelEn: 'Funds transferred/disbursed',
        level: 'blocking',
        sourceType: 'legal',
        step: 7,
        appliesWhen: {},
        pack: 'universal',
        order: 2,
        isDefault: true,
        isActive: true,
        deadlineReference: 'closing',
        defaultDeadlineDays: 0, // On closing day
      },
      {
        labelFr: 'Remise des clés',
        labelEn: 'Keys delivered',
        level: 'blocking',
        sourceType: 'industry',
        step: 7,
        appliesWhen: {},
        pack: 'universal',
        order: 3,
        isDefault: true,
        isActive: true,
        deadlineReference: 'closing',
        defaultDeadlineDays: 0, // On closing day
      },

      // Step 8: Post-clôture
      {
        labelFr: 'Suivi 7 jours + 30 jours',
        labelEn: '7-day + 30-day follow-up',
        level: 'recommended',
        sourceType: 'best_practice',
        step: 8,
        appliesWhen: {},
        pack: 'universal',
        order: 1,
        isDefault: true,
        isActive: true,
        deadlineReference: 'closing',
        defaultDeadlineDays: 7, // 7 days after closing for first follow-up
      },
    ])

    // ============================================================
    // PACK RURAL NB v1.0
    // ============================================================

    await ConditionTemplate.createMany([
      // Step 3: Offre Acceptée - Well/Septic
      {
        labelFr: 'Test de qualité d\'eau commandé',
        labelEn: 'Water quality test ordered',
        level: 'required',
        sourceType: 'government',
        step: 3,
        appliesWhen: { property_context: 'rural', has_well: true },
        pack: 'rural_nb',
        order: 1,
        isDefault: true,
        isActive: true,
        deadlineReference: 'acceptance',
        defaultDeadlineDays: 3, // Order within 3 days
      },
      {
        labelFr: 'Test de qualité d\'eau — résultats acceptables',
        labelEn: 'Water quality test — acceptable results',
        level: 'blocking',
        sourceType: 'government',
        step: 3,
        appliesWhen: { property_context: 'rural', has_well: true },
        pack: 'rural_nb',
        order: 2,
        isDefault: true,
        isActive: true,
        deadlineReference: 'acceptance',
        defaultDeadlineDays: 10, // Results within 10 days
      },
      {
        labelFr: 'Test de débit du puits commandé',
        labelEn: 'Well flow test ordered',
        level: 'required',
        sourceType: 'industry',
        step: 3,
        appliesWhen: { property_context: 'rural', has_well: true },
        pack: 'rural_nb',
        order: 3,
        isDefault: true,
        isActive: true,
        deadlineReference: 'acceptance',
        defaultDeadlineDays: 3,
      },
      {
        labelFr: 'Test de débit du puits — résultats acceptables',
        labelEn: 'Well flow test — acceptable results',
        level: 'blocking',
        sourceType: 'industry',
        step: 3,
        appliesWhen: { property_context: 'rural', has_well: true },
        pack: 'rural_nb',
        order: 4,
        isDefault: true,
        isActive: true,
        deadlineReference: 'acceptance',
        defaultDeadlineDays: 10,
      },
      {
        labelFr: 'Inspection fosse septique commandée',
        labelEn: 'Septic inspection ordered',
        level: 'required',
        sourceType: 'government',
        step: 3,
        appliesWhen: { property_context: 'rural', has_septic: true },
        pack: 'rural_nb',
        order: 5,
        isDefault: true,
        isActive: true,
        deadlineReference: 'acceptance',
        defaultDeadlineDays: 3,
      },
      {
        labelFr: 'Inspection fosse septique — résultats acceptables',
        labelEn: 'Septic inspection — acceptable results',
        level: 'blocking',
        sourceType: 'government',
        step: 3,
        appliesWhen: { property_context: 'rural', has_septic: true },
        pack: 'rural_nb',
        order: 6,
        isDefault: true,
        isActive: true,
        deadlineReference: 'acceptance',
        defaultDeadlineDays: 10,
      },

      // Right of Way conditions
      {
        labelFr: 'Servitude de passage — document obtenu',
        labelEn: 'Right of way — document obtained',
        level: 'blocking',
        sourceType: 'legal',
        step: 3,
        appliesWhen: { property_context: 'rural', access_type: 'right_of_way' },
        pack: 'rural_nb',
        order: 10,
        isDefault: true,
        isActive: true,
        deadlineReference: 'acceptance',
        defaultDeadlineDays: 10,
      },
      {
        labelFr: 'Entente d\'entretien chemin privé — signée',
        labelEn: 'Private road maintenance agreement — signed',
        level: 'required',
        sourceType: 'legal',
        step: 3,
        appliesWhen: { property_context: 'rural', access_type: 'private' },
        pack: 'rural_nb',
        order: 11,
        isDefault: true,
        isActive: true,
        deadlineReference: 'acceptance',
        defaultDeadlineDays: 10,
      },

      // Step 4: Période Conditionnelle
      {
        labelFr: 'Conditions levées par écrit',
        labelEn: 'Conditions waived in writing',
        level: 'blocking',
        sourceType: 'legal',
        step: 4,
        appliesWhen: { property_context: 'rural' },
        pack: 'rural_nb',
        order: 1,
        isDefault: true,
        isActive: true,
        deadlineReference: 'acceptance',
        defaultDeadlineDays: 10,
      },

      // Step 6: Pré-clôture
      {
        labelFr: 'Visite pré-fermeture complétée',
        labelEn: 'Pre-closing walkthrough completed',
        level: 'recommended',
        sourceType: 'best_practice',
        step: 6,
        appliesWhen: { property_context: 'rural' },
        pack: 'rural_nb',
        order: 1,
        isDefault: true,
        isActive: true,
        deadlineReference: 'closing',
        defaultDeadlineDays: -2, // 2 days before closing
      },
    ])

    // ============================================================
    // PACK CONDO NB v1.0
    // ============================================================

    await ConditionTemplate.createMany([
      // Step 3: Offre Acceptée - Condo Documents
      {
        labelFr: 'Demande documents condo envoyée',
        labelEn: 'Condo documents request sent',
        level: 'required',
        sourceType: 'industry',
        step: 3,
        appliesWhen: { property_type: 'condo' },
        pack: 'condo_nb',
        order: 1,
        isDefault: true,
        isActive: true,
        deadlineReference: 'acceptance',
        defaultDeadlineDays: 2,
      },
      {
        labelFr: 'Déclaration / By-laws / Rules reçus',
        labelEn: 'Declaration / By-laws / Rules received',
        level: 'required',
        sourceType: 'industry',
        step: 3,
        appliesWhen: { property_type: 'condo' },
        pack: 'condo_nb',
        order: 2,
        isDefault: true,
        isActive: true,
        deadlineReference: 'acceptance',
        defaultDeadlineDays: 7,
      },
      {
        labelFr: 'Budget + états financiers reçus',
        labelEn: 'Budget + financial statements received',
        level: 'required',
        sourceType: 'industry',
        step: 3,
        appliesWhen: { property_type: 'condo' },
        pack: 'condo_nb',
        order: 3,
        isDefault: true,
        isActive: true,
        deadlineReference: 'acceptance',
        defaultDeadlineDays: 7,
      },
      {
        labelFr: 'Procès-verbaux (12–24 mois) reçus',
        labelEn: 'Minutes (12–24 months) received',
        level: 'required',
        sourceType: 'industry',
        step: 3,
        appliesWhen: { property_type: 'condo' },
        pack: 'condo_nb',
        order: 4,
        isDefault: true,
        isActive: true,
        deadlineReference: 'acceptance',
        defaultDeadlineDays: 7,
      },
      {
        labelFr: 'Certificat Estoppel / Status Certificate reçu',
        labelEn: 'Estoppel Certificate / Status Certificate received',
        level: 'blocking',
        sourceType: 'legal',
        step: 3,
        appliesWhen: { property_type: 'condo', is_financed: true },
        pack: 'condo_nb',
        order: 5,
        isDefault: true,
        isActive: true,
        deadlineReference: 'acceptance',
        defaultDeadlineDays: 10,
      },
      {
        labelFr: 'Frais condo confirmés (mensuels + inclusions)',
        labelEn: 'Condo fees confirmed (monthly + inclusions)',
        level: 'required',
        sourceType: 'industry',
        step: 3,
        appliesWhen: { property_type: 'condo' },
        pack: 'condo_nb',
        order: 6,
        isDefault: true,
        isActive: true,
        deadlineReference: 'acceptance',
        defaultDeadlineDays: 7,
      },
      {
        labelFr: 'Fonds de réserve / plan de maintien — vérifié',
        labelEn: 'Reserve fund / capital plan reviewed',
        level: 'required',
        sourceType: 'industry',
        step: 3,
        appliesWhen: { property_type: 'condo' },
        pack: 'condo_nb',
        order: 7,
        isDefault: true,
        isActive: true,
        deadlineReference: 'acceptance',
        defaultDeadlineDays: 10,
      },
      {
        labelFr: 'Avis de cotisation spéciale (special assessment) — vérifié',
        labelEn: 'Special assessment notices checked',
        level: 'required',
        sourceType: 'industry',
        step: 3,
        appliesWhen: { property_type: 'condo' },
        pack: 'condo_nb',
        order: 8,
        isDefault: true,
        isActive: true,
        deadlineReference: 'acceptance',
        defaultDeadlineDays: 10,
      },
      {
        labelFr: 'Approbation acheteur des docs condo (écrit)',
        labelEn: 'Buyer approval of condo docs (in writing)',
        level: 'blocking',
        sourceType: 'legal',
        step: 3,
        appliesWhen: { property_type: 'condo' },
        pack: 'condo_nb',
        order: 20,
        isDefault: true,
        isActive: true,
        deadlineReference: 'acceptance',
        defaultDeadlineDays: 10,
      },

      // Step 4: Période Conditionnelle
      {
        labelFr: 'Analyse documents condo complétée (checklist)',
        labelEn: 'Condo document review completed (checklist)',
        level: 'blocking',
        sourceType: 'best_practice',
        step: 4,
        appliesWhen: { property_type: 'condo' },
        pack: 'condo_nb',
        order: 1,
        isDefault: true,
        isActive: true,
        deadlineReference: 'acceptance',
        defaultDeadlineDays: 10,
      },
      {
        labelFr: 'Conditions levées par écrit',
        labelEn: 'Conditions waived in writing',
        level: 'blocking',
        sourceType: 'legal',
        step: 4,
        appliesWhen: { property_type: 'condo' },
        pack: 'condo_nb',
        order: 2,
        isDefault: true,
        isActive: true,
        deadlineReference: 'acceptance',
        defaultDeadlineDays: 10,
      },

      // Step 6: Pré-clôture
      {
        labelFr: 'Prêteur satisfait des docs condo',
        labelEn: 'Lender satisfied with condo docs',
        level: 'blocking',
        sourceType: 'industry',
        step: 6,
        appliesWhen: { property_type: 'condo', is_financed: true },
        pack: 'condo_nb',
        order: 1,
        isDefault: true,
        isActive: true,
        deadlineReference: 'closing',
        defaultDeadlineDays: -5, // 5 days before closing
      },
      {
        labelFr: 'Visite pré-fermeture unité complétée',
        labelEn: 'Pre-closing walkthrough completed',
        level: 'recommended',
        sourceType: 'best_practice',
        step: 6,
        appliesWhen: { property_type: 'condo' },
        pack: 'condo_nb',
        order: 10,
        isDefault: true,
        isActive: true,
        deadlineReference: 'closing',
        defaultDeadlineDays: -2,
      },

      // Step 7: Jour de clôture
      {
        labelFr: 'Remise des clés / fobs / accès',
        labelEn: 'Keys / fobs / access delivered',
        level: 'blocking',
        sourceType: 'industry',
        step: 7,
        appliesWhen: { property_type: 'condo' },
        pack: 'condo_nb',
        order: 4,
        isDefault: true,
        isActive: true,
        deadlineReference: 'closing',
        defaultDeadlineDays: 0,
      },
    ])

    // ============================================================
    // PACK FINANCÉ NB v1.0
    // ============================================================

    await ConditionTemplate.createMany([
      // Step 3: Offre Acceptée
      {
        labelFr: 'Lettre d\'engagement / Mortgage Commitment reçu',
        labelEn: 'Mortgage Commitment received',
        level: 'blocking',
        sourceType: 'industry',
        step: 3,
        appliesWhen: { is_financed: true },
        pack: 'finance_nb',
        order: 1,
        isDefault: true,
        isActive: true,
        deadlineReference: 'acceptance',
        defaultDeadlineDays: 10, // 10 days for financing condition
      },
      {
        labelFr: 'Preuve fonds / down payment (si requis)',
        labelEn: 'Proof of funds / down payment (if required)',
        level: 'required',
        sourceType: 'industry',
        step: 3,
        appliesWhen: { is_financed: true },
        pack: 'finance_nb',
        order: 2,
        isDefault: true,
        isActive: true,
        deadlineReference: 'acceptance',
        defaultDeadlineDays: 5,
      },
      {
        labelFr: 'Appraisal commandé',
        labelEn: 'Appraisal ordered',
        level: 'required',
        sourceType: 'industry',
        step: 3,
        appliesWhen: { is_financed: true, appraisal_required: true },
        pack: 'finance_nb',
        order: 3,
        isDefault: true,
        isActive: true,
        deadlineReference: 'acceptance',
        defaultDeadlineDays: 3,
      },
      {
        labelFr: 'Appraisal reçu et acceptable',
        labelEn: 'Appraisal received and acceptable',
        level: 'blocking',
        sourceType: 'industry',
        step: 3,
        appliesWhen: { is_financed: true, appraisal_required: true },
        pack: 'finance_nb',
        order: 4,
        isDefault: true,
        isActive: true,
        deadlineReference: 'acceptance',
        defaultDeadlineDays: 10,
      },

      // Step 4: Période Conditionnelle
      {
        labelFr: 'Conditions prêteur satisfaites (final approval)',
        labelEn: 'Lender conditions satisfied (final approval)',
        level: 'blocking',
        sourceType: 'industry',
        step: 4,
        appliesWhen: { is_financed: true },
        pack: 'finance_nb',
        order: 1,
        isDefault: true,
        isActive: true,
        deadlineReference: 'acceptance',
        defaultDeadlineDays: 10,
      },
      {
        labelFr: 'Assurance habitation "pré-validation" complétée',
        labelEn: 'Home insurance pre-validation completed',
        level: 'required',
        sourceType: 'industry',
        step: 4,
        appliesWhen: { is_financed: true },
        pack: 'finance_nb',
        order: 2,
        isDefault: true,
        isActive: true,
        deadlineReference: 'acceptance',
        defaultDeadlineDays: 10,
      },
      {
        labelFr: 'Conditions levées par écrit',
        labelEn: 'Conditions waived in writing',
        level: 'blocking',
        sourceType: 'legal',
        step: 4,
        appliesWhen: { is_financed: true },
        pack: 'finance_nb',
        order: 10,
        isDefault: true,
        isActive: true,
        deadlineReference: 'acceptance',
        defaultDeadlineDays: 10,
      },

      // Step 5: Ferme en attente
      {
        labelFr: 'Title search lancé (par avocat)',
        labelEn: 'Title search initiated (by lawyer)',
        level: 'required',
        sourceType: 'legal',
        step: 5,
        appliesWhen: { is_financed: true },
        pack: 'finance_nb',
        order: 2,
        isDefault: true,
        isActive: true,
        deadlineReference: 'closing',
        defaultDeadlineDays: -21, // 3 weeks before closing
      },
      {
        labelFr: 'Instruction banque ↔ avocat confirmée',
        labelEn: 'Bank ↔ lawyer closing coordination confirmed',
        level: 'required',
        sourceType: 'industry',
        step: 5,
        appliesWhen: { is_financed: true },
        pack: 'finance_nb',
        order: 3,
        isDefault: true,
        isActive: true,
        deadlineReference: 'closing',
        defaultDeadlineDays: -14,
      },

      // Step 6: Pré-clôture
      {
        labelFr: 'Assurance habitation confirmée (bind)',
        labelEn: 'Home insurance bound/confirmed',
        level: 'blocking',
        sourceType: 'industry',
        step: 6,
        appliesWhen: { is_financed: true },
        pack: 'finance_nb',
        order: 1,
        isDefault: true,
        isActive: true,
        deadlineReference: 'closing',
        defaultDeadlineDays: -5,
      },
      {
        labelFr: 'Montant final + instructions banque confirmés',
        labelEn: 'Final amount + bank instructions confirmed',
        level: 'blocking',
        sourceType: 'industry',
        step: 6,
        appliesWhen: { is_financed: true },
        pack: 'finance_nb',
        order: 2,
        isDefault: true,
        isActive: true,
        deadlineReference: 'closing',
        defaultDeadlineDays: -3,
      },
      {
        labelFr: 'Fonds disponibles confirmés (down payment + frais)',
        labelEn: 'Funds available confirmed (down payment + costs)',
        level: 'blocking',
        sourceType: 'industry',
        step: 6,
        appliesWhen: { is_financed: true },
        pack: 'finance_nb',
        order: 3,
        isDefault: true,
        isActive: true,
        deadlineReference: 'closing',
        defaultDeadlineDays: -3,
      },
      {
        labelFr: 'Statement of adjustments prêt',
        labelEn: 'Statement of adjustments ready',
        level: 'required',
        sourceType: 'legal',
        step: 6,
        appliesWhen: { is_financed: true },
        pack: 'finance_nb',
        order: 4,
        isDefault: true,
        isActive: true,
        deadlineReference: 'closing',
        defaultDeadlineDays: -2,
      },

      // Step 8: Post-clôture
      {
        labelFr: 'Confirmation client: paiements hypothèque en place',
        labelEn: 'Client confirmation: mortgage payments set up',
        level: 'recommended',
        sourceType: 'best_practice',
        step: 8,
        appliesWhen: { is_financed: true },
        pack: 'finance_nb',
        order: 1,
        isDefault: true,
        isActive: true,
        deadlineReference: 'closing',
        defaultDeadlineDays: 30, // First mortgage payment usually 30 days after
      },
    ])

    console.log('✅ Condition templates seeded successfully!')
    console.log('   - Pack Universal: 11 (étapes 2-8)')
    console.log('   - Pack Rural NB: 12')
    console.log('   - Pack Condo NB: 15')
    console.log('   - Pack Financé NB: 14')
    console.log('   - Total: 52 templates')
  }
}
